spring:
  profiles:
    active: dev

backend:
  account: 'Johnny'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: backend-base
    username: root
    password: 123456aA
  url: 127.0.0.1
  security:
    security:
      jwt:
        key: 'Johnny'
        expire: 72
      user:
        name: 123
        password: 123
  mail:
    host: "smtp.qq.com"
    port: 25
    username: 525860438@qq.com
    password: 123456aA